name: Update README Status

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        run: |
          # Select a random line from status.txt
          STATUS=$(shuf -n 1 status.txt)
          awk -v status="$STATUS" '
          /<!-- STATUS:START -->/ {print; print status; skip=1}
          /<!-- STATUS:END -->/ {skip=0}
          !skip {print}
          ' README.md > temp.md
          mv temp.md README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update live status" || echo "No changes"
          git push
